apiVersion: v1
description: fluxcd-demo
name: fluxcd-demo
version: 0.0.1-dev
appVersion: 0.0.1-dev
dependencies:
- name: netassert
  repository: oci://ghcr.io/controlplaneio/charts
  version: <version>
