kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."host.docker.internal:5050"]
      endpoint = ["http://host.docker.internal:5050"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."host.docker.internal:5050"]
      insecure_skip_verify = true