apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netassert
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - deployments
  - statefulsets
  - daemonsets
  - pods
  verbs:
  - get
##
- apiGroups:
  - ""
  - "apps"
  resources:
  - replicasets
  - pods
  verbs:
  - list
##
- apiGroups:
  - ""
  resources:
  - pods
  - pods/ephemeralcontainers
  verbs:
  - watch
  - patch
