apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "netassert.fullname" . }}
  labels:
    app: {{ template "netassert.name" . }}
    chart: {{ template "netassert.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  parallelism: {{ .Values.job.parallelism }}
  completions: {{ .Values.job.completions }}
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        app: {{ template "netassert.name" . }}
        release: {{ .Release.Name }}
        component: job
    spec:
      restartPolicy: {{ default "Never" .Values.job.restartPolicy }}
      serviceAccount: {{ template "netassert.fullname" . }}
      securityContext:
        {{ toYaml .Values.securityContext | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      containers:
        - name: netassert
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{ toYaml .Values.args | nindent 12 }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ $value | quote }}
          {{- end }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: testfile
              mountPath: /tests
            {{- if .Values.volumeMounts }}
            {{ toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: testfile
          configMap:
            name: {{ template "netassert.fullname" . }}
        {{- if .Values.volumes }}
        {{ toYaml .Values.volumes | nindent 8 }}
        {{- end }}
        {{- range $key, $value := .Values.secretMounts }}
        - name: {{ $key }}
          secret:
            secretName: {{ $value.secretName }}
            defaultMode: {{ $value.defaultMode }}
        {{- end }}