apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
    role: frontend
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
        app: web
        role: frontend
  template:
    metadata:
      labels:
        app: web
        role: frontend
    spec:
      containers:
      - args:
        - sh
        - -c
        - while true; do { printf 'HTTP/1.1 200 OK\r\n\n I am a frontend\n'; } | nc -l -p  80; done
        image: busybox
        name: alpine
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
    role: microservice
  name: microservice
spec:
  replicas: 3
  selector:
    matchLabels:
        app: web
        role: microservice
  template:
    metadata:
      labels:
        app: web
        role: microservice
    spec:
      containers:
      - args:
        - sh
        - -c
        - while true; do { printf 'HTTP/1.1 200 OK\r\n\n I am a microservice\n'; } | nc -l -p  80; done
        image: busybox
        name: alpine
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
    role: database
  name: database
spec:
  replicas: 3
  selector:
    matchLabels:
        app: web
        role: database
  template:
    metadata:
      labels:
        app: web
        role: database
    spec:
      containers:
      - args:
        - sh
        - -c
        - while true; do { printf 'HTTP/1.1 200 OK\r\n\n I am a database\n'; } | nc -l -p  80; done
        image: busybox
        name: alpine
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        ports:
        - containerPort: 80
          protocol: TCP
